/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test3;
import java.io.Reader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception{
        System.out.println(new App().getGreeting());

    }
}
