/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test3;


import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.MatcherAssert.*;
import static org.hamcrest.Matchers.equalTo;
import java.util.ArrayList;

public class DictionaryTest {
//Il faut competer
    private Dictionary dict;
    @Before
    public void initialize(){
        //dict = new Dictionary("Example");
        dict = null;
    }
    @Test public void Isempty(){
        assertNotNull("dict not null",dict);
    }
    @Test public void testDictionaryName(){
        System.out.println(dict.getName());
        assertThat(dict.getName(),equalTo("Example"));
    }
}
